# Site settings
title: Den Official Website # site title
description: >- # site description
  This is the official page of the Den professional pixel artist.
lang: en # default lang
timezone: Europe/Madrid # default timezone
image: /assets/img/denpixelart.png # This image used for Open Graph more info https://ogp.me/
mode: light # default theme "dark" | "light"

in_maintainment: true # true | false to show maintaince message

# Profile settings
author:
  name: Den PixelArt # author name
  bio: >- # tell to the world
    Pixel Artist - Indie Game Developer - Game Designer - Game Programmer 
  username: DenPixelArt # general username
  github: DenPixelArt # github username
  twitter: Den_pixel # twitter username
  instagram: DenPixelArt # facebook username
  email: denpixelart@gmail.com # email adress
  avatar: /assets/img/Woolficon.png # change with your own avatar
  itchio_url: https://denpixelart.itch.io # itch.io url 

# URL settings
url: "https://denpixelart.com" #
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec
  - vendor

# Added temporary to avoid build error
future: false

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
